### ISSUE TITLE
New distortion correction

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/comp-pipeline#18]
Find new distortion coefficients.

**Comment by mgalloy** [comment]
Steve says:
> I am still working on the distortion

**Comment by mgalloy** [comment]
The new distortion correction is in the distortion branch and has been merged into the geometry branch.

**Comment by mgalloy** [comment]
The new distortion correction is working in c6fb1adba032c784095a8651ccae5fa48dcd4e18.

**Comment by jburkepile** [comment]
Thanks for the comments on these tickets Mike. We can go over them 
quickly on Monday and hopefully close them.

cheers!
joan
