### ISSUE TITLE
Add keyword to L1 files indicating how Q/U have been processed

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/comp-pipeline#32]
Joan says:

> ... we should add a keyword to the current CoMP headers so we know when Mike has reprocessed Q,U with the polarimetric helio transform. Since that is unique to CoMP we can call the keyword whatever we want.

**Comment by mgalloy** [comment]
Need a polarization axis keyword; ask Steve.

Also, maybe we should more 45 degree constant from `COMP_AZIMUTH` to Q/U correction.

**Comment by mgalloy** [comment]
Steve said:
> As for the fits keyword, maybe we should use something relating to the polarization coordinate frame being either geocentric or heliocentric. POLFRAME or POLCOORD?

**Comment by mgalloy** [comment]
Steve says:
> On second thought, the coordinate in POLCOORD sounds geometric and may be confusing. Maybe it would be better if we called the keyword POLFRAME and we could refer to it as the polarization reference frame. What do you think?

**Comment by mgalloy** [comment]
Sure, so:

    POLFRAME   'heliocentric'  / Polarization reference frame
    POLFRAME   'geocentric'    / Polarization reference frame

I will update the code.

**Comment by jburkepile** [comment]
I am okay with POLFRAME. Its important that we come up with a keyword 
comment in the header that  is clear to the user.
