### ISSUE TITLE
Check headers for consistent time format

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/comp-pipeline#4]
The format in the FITS headers should be like:

    DATE_OBS=          '2/26/2015' / DATE OF OBSERVATION                            
    TIME_OBS=         '8:29:14 AM' / TIME OF OBSERVATION

**Comment by mgalloy** [comment]
Giuliana has checked 2014, 2013, and part of 2012.

**Comment by astanger** [comment]
dd/mm/yyyy is a NON-standard format for the date in FITS headers.  The
preferred format is yyyy-mm-dd, with leading zeroes for numbers below 10.

--- Andrew

**Comment by mgalloy** [comment]
Definitely, but this is from the raw FITS headers which I don't think we have control of. My understanding is that that format is all we can get.
