### ISSUE TITLE
Centering off in flat

### ISSUE THREAD

**Issue by mgalloy** [ncar-mlso/comp-pipeline#63]
The center coordinates are incorrect in the flat headers for both the distortion corrected and distortion uncorrected images. Possibly because we subtract the initial guess. The centering code should be changed so it gives back the center coordinates in 620x620, not the offset from the middle of the array. This will make the code easier to read. The routines that use its output shall be changed accordingly. The guess shall be used only to find the center and in none of the other routines.

**Comment by mgalloy** [comment]
Check `center_guess` in last lines of `comp_find_image_center`.

**Comment by detoma** [comment]
changed code to find center
