### ISSUE TITLE
Fix PNG for dashboard

### ISSUE THREAD

**Issue by detoma** [ncar-mlso/comp-pipeline#67]
The PNG for the line-width and enhanced intensity appear messed up in the latest version of the code.

**Comment by mgalloy** [comment]
`MPFITFUN` in `COMP_INTENSITY_ENHANCEMENT` was failing to converge for some days, i.e., 20171001. Using `/NAN` keyword in `MPFITFUN` fixes this. Also, returning status and error message from `COMP_INTENSITY_ENHANCEMENT` to log.
