### ISSUE TITLE
Compute overlap_angle from field data 

### ISSUE THREAD

**Issue by detoma** [ncar-mlso/comp-pipeline#71]
We currently compute overlap angle from occulter center, we should use field center but only available for flat. We can compute field center for science images and test if robust. If so, this solves the issue.

**Comment by mgalloy** [comment]
Try to compute the field center and pass back from `COMP_ANNULUS` to use in `COMP_IMAGE_GEOMETRY` to compute `overlap_angle`.

**Comment by mgalloy** [comment]
The `overlap_angle` branch has this change and can find an overlap angle, but using the field center appears to be the same as using the occulter center.

**Comment by mgalloy** [comment]
Merged the `overlap_branch`, closing ticket.
