### ISSUE TITLE
Check integrity of older level 0 FITS headers

### ISSUE THREAD

**Issue by jburkepile** [ncar-mlso/comp-pipeline#77]
Spot check older primary and extension headers for existence and values of keywords.

**Comment by mgalloy** [comment]
@jburkepile:

> COMP Header changes AFTER Dec 1, 2012:
>
> ALL TIMES IN HST
>
> PRIMARY HEADER
> --------------
>
> OBS_ID: Added Sept 11, 2015  11:05:46 HST ** BUT ** its reliable or has no value. 
>         It is not in quotes and its value depends on the first character used in the string. 
> 	If its a letter it reads it in as a string; if its a number it reads it in as a LONG 
> 	and clips off any values that are not a number
> OBS_ID: Quotes NEVER added 
>
>
> OS_PLAN:  Keyword added is a typo. Sept 11, 2015 11:05:46 HST 
> OBS_PLAN: Correct keyword added Sept 11, 2015 11:08:51 HST Value is not in quotes but I CAN 
>           read them in using sxpar because the value always begins with a letter
> OBS_PLAN: Quotes NEVER added
>
>
> 01FOCS:  Added May 11, 2016 10:35:30 HST
>
>
> EXTENSION HEADER
> -----------------
>
> NDFILTER: Added Sept 25, 2015 at 12:05:38 HST  ** BUT ** It has no value
>
> NDFILTER: Sep 25, 2015 at 12:10:15 HST   Is okay to use as it has a proper value
>
> NDFILTER: Erroneously set to '0' from May 11, 2016 14:06:03 to 14:30:28 HST AND POSSIBLY 
>           OTHER TIMES THIS DAY. When it is set to '0' it  SHOULD BE = '8'

**Comment by mgalloy** [comment]
`COMP_GET_NDFILTER` needs to be adjusted to handle 1083.
