### ISSUE TITLE
Capture distortion info in primary header

### ISSUE THREAD

**Issue by jburkepile** [ncar-mlso/comp-pipeline#91]
Create new FITS keyword in L1 primary header and list distortion file used or distortion coefficient(s).

**Comment by mgalloy** [comment]
Distortion can now be specified via the config file and is put into the L1 primary headers. For method "coeffs", the header reads:

    DISTMETH= 'coeffs  '           / method used for distortion correction
    DISTC1  =              0.99353 / distortion coefficient 1                       
    DISTC2  =              1.00973 / distortion coefficient 2

For method "file", the header is:

    DISTMETH= 'file    '           / method used for distortion correction          
    DISTFILE= 'dist_coeff_20161107.sav' / file containing distortion coefficients

For method "none", the header is:

    DISTMETH= 'none    '           / method used for distortion correction

**Comment by mgalloy** [comment]
FITS keywords/comments look OK to @jburkepile.
